In [1]:
import os
import pandas as pd

In [3]:
# Define the input_folder where the CSV files are stored
input_folder = r"C:\Users\nwn86\ResearchProject_singlensp\Staging\Energy"  # Change this to your actual path

In [5]:
input_folder

'C:\\Users\\nwn86\\ResearchProject_singlensp\\Staging\\Energy'

In [7]:
# Initialize an empty list to store individual DataFrames
dfs = []

# Loop through all CSV files in the input_folder
for filename in os.listdir(input_folder):
    if filename.endswith(".csv"):
        file_path = os.path.join(input_folder, filename)
        df = pd.read_csv(file_path, parse_dates=["Trading_date"])
        dfs.append(df)

# Concatenate all DataFrames into a single DataFrame
merged_df = pd.concat(dfs, ignore_index=True)

# Ensure the data is sorted by Trading_date
merged_df.sort_values(by="Trading_date", inplace=True)

In [9]:
merged_df

       Fuel_Code POC_Code Trading_date   Total_TP
0          Hydro  ANI0111   2000-01-01   352663.0
217        Hydro  BWK1101   2000-01-01    63952.0
372        Hydro  KPO1101   2000-01-01   940750.0
403        Hydro  KUM0111   2000-01-01    87503.0
899        Hydro  TUI1101   2000-01-01   942570.0
...          ...      ...          ...        ...
377633     Hydro  TKB2201   2025-01-31  2317178.0
377013     Hydro  CYD2201   2025-01-31  3547678.0
377602     Hydro  TKA0111   2025-01-31   460917.0
377819     Hydro  WTK0111   2025-01-31  1610301.0
378222      Wind  WWD1103   2025-01-31   544447.0

[378223 rows x 4 columns]

In [11]:
# # Filter data within the specified date range
# start_date = "2015-01-01"
# end_date = "2024-12-31"
# merged_df = merged_df[(merged_df["Trading_date"] >= start_date) & (merged_df["Trading_date"] <= end_date)]

In [13]:
merged_df = merged_df.rename(columns={'Trading_date': 'DATE'})

In [15]:
merged_df['Total_TP'] = merged_df['Total_TP'].round(4)

In [17]:
merged_df

       Fuel_Code POC_Code       DATE   Total_TP
0          Hydro  ANI0111 2000-01-01   352663.0
217        Hydro  BWK1101 2000-01-01    63952.0
372        Hydro  KPO1101 2000-01-01   940750.0
403        Hydro  KUM0111 2000-01-01    87503.0
899        Hydro  TUI1101 2000-01-01   942570.0
...          ...      ...        ...        ...
377633     Hydro  TKB2201 2025-01-31  2317178.0
377013     Hydro  CYD2201 2025-01-31  3547678.0
377602     Hydro  TKA0111 2025-01-31   460917.0
377819     Hydro  WTK0111 2025-01-31  1610301.0
378222      Wind  WWD1103 2025-01-31   544447.0

[378223 rows x 4 columns]

In [19]:
_dir = r"C:\Users\nwn86\ResearchProject_singlensp\Processed"
# Save the merged DataFrame to a new CSV file
filename = "merged_data.csv"

output_file = os.path.join(_dir, filename)

merged_df.to_csv(output_file, index=False)

print(f"Merged CSV file saved as {output_file}")

Merged CSV file saved as C:\Users\nwn86\ResearchProject_singlensp\Processed\merged_data.csv

In [21]:
nsp_info = pd.read_csv(r"C:\Users\nwn86\ResearchProject_singlensp\Input\nsp_info_final_v1.csv")

In [23]:
nsp_info

,POC_Code,NZTM_easting,NZTM_northing,Network,Island,Fuel_Code,Latitude,Longitude
0,ARA2201,1873657.0,5721160.0,Taupo (Unison Networks),NI,Hydro,-38.615891,176.143036
1,ARG1101,1616836.0,5386748.0,Marlborough (Marlborough Lines),SI,Hydro,-41.670851,173.202251
2,ARI1101,1831834.0,5782895.0,Thames Valley (Powerco),NI,Hydro,-38.072026,175.642919
3,ARI1102,1831834.0,5782895.0,Thames Valley (Powerco),NI,Hydro,-38.072026,175.642919
4,ASB0661,1503869.0,5133912.0,Ashburton (Electricity Ashburton),SI,Hydro,-43.941637,171.802149
5,ATI2201,1863994.0,5746271.0,King Country (The Lines Company),NI,Hydro,-38.392831,176.022730
6,AVI2201,1390245.0,5051586.0,Waitaki (Network Waitaki),SI,Hydro,-44.658443,170.354335
7,BEN2202,1377144.0,5061473.0,Waitaki (Network Waitaki),SI,Hydro,-44.565596,170.193571
8,BPE0331,1824481.0,5537751.0,Manawatu (Powerco),NI,Wind,-40.280614,175.640510
9,BWK1101,1375377.0,4908483.0,Dunedin (Aurora Energy),SI,Hydro,-45.940470,170.102172
10,COL0661,1480658.0,5197735.0,Central Canterbury (Orion New Zealand),SI,Hydro,-43.363766,171.527122
11,CYD0331,1309790.0,4990370.0,Central Otago (Aurora Energy),SI,Hydro,-45.180391,169.306224
12,CYD2201,1309790.0,4990370.0,Central Otago (Aurora Energy),SI,Hydro,-45.180391,169.306224
13,EDG0331,1936285.0,5788677.0,Eastern Bay of Plenty (Horizon Energy),NI,Solar,-37.987259,176.828883
14,GOR0331,1284097.0,4885035.0,Southland (The Power Company),SI,Wind,-46.115091,168.911652
15,HWA1101,1712537.0,5619536.0,Taranaki (Powerco),NI,Hydro,-39.566497,174.310117
16,HWB0331,1404029.0,4918978.0,Dunedin (Aurora Energy),SI,Hydro,-45.854874,170.475700
17,HWB0331,1404029.0,4918978.0,Otago (OtagoNet JV),SI,Hydro,-45.854874,170.475700
18,KOE1101,1673614.0,6082721.0,Bay of Islands (Top Energy),NI,Solar,-35.396162,173.810632
19,KPO1101,1823029.0,5799542.0,Thames Valley (Powerco),NI,Hydro,-37.924349,175.537461
20,LTN0331,1823277.0,5523360.0,Manawatu (Powerco),NI,Wind,-40.410452,175.631394
21,LTN2201,1823277.0,5523360.0,Manawatu (Powerco),NI,Wind,-40.410452,175.631394
22,MAN2201,1153098.0,4943235.0,Southland (The Power Company),SI,Hydro,-45.520868,167.277500
23,MAT1101,1934456.0,5774722.0,Eastern Bay of Plenty (Horizon Energy),NI,Hydro,-38.113429,176.814617
24,MHO0331,1807281.0,5505363.0,Kapiti and Horowhenua (Electra),NI,Hydro,-40.576575,175.448930
25,MTI2201,1839802.0,5751482.0,King Country (The Lines Company),NI,Hydro,-38.352736,175.744267
26,NMA0331,1242677.0,4861547.0,Southland (The Power Company),SI,Wind,-46.305391,168.359527
27,NSY0331,1371044.0,5009253.0,Otago (OtagoNet JV),SI,Hydro,-45.033180,170.093353
28,OHA2201,1362883.0,5094304.0,South Canterbury (Alpine Energy),SI,Hydro,-44.265872,170.029212
29,OHB2201,1369516.0,5090545.0,Waitaki (Network Waitaki),SI,Hydro,-44.301801,170.110551
30,OHC2201,1375175.0,5086098.0,Waitaki (Network Waitaki),SI,Hydro,-44.343561,170.179492
31,OHK2201,1869462.0,5744408.0,Rotorua (Unison Networks),NI,Hydro,-38.407966,176.085969
32,ROT1101,1882790.0,5772814.0,Rotorua (Unison Networks),NI,Hydro,-38.148250,176.227041
33,ROX1101,1312313.0,4957442.0,Central Otago (Aurora Energy),SI,Hydro,-45.477213,169.319136
34,ROX2201,1312313.0,4957442.0,Central Otago (Aurora Energy),SI,Hydro,-45.477213,169.319136
35,RPO2201,1845189.0,5662388.0,King Country (The Lines Company),NI,Hydro,-39.153194,175.837443
36,STK0661,1620344.0,5426252.0,Tasman (Network Tasman),SI,Hydro,-41.314941,173.243059
37,TGA0331,1875930.0,5819779.0,Tauranga (Powerco),NI,Hydro,-37.727716,176.130869
38,TKA0111,1396471.0,5123459.0,South Canterbury (Alpine Energy),SI,Hydro,-44.013807,170.460853
39,TKB2201,1376922.0,5110445.0,South Canterbury (Alpine Energy),SI,Hydro,-44.125161,170.211748
40,TKU2201,1839960.0,5681601.0,King Country (The Lines Company),NI,Hydro,-38.981721,175.770224
41,TUI1101,1960528.0,5696630.0,Eastland (Eastland Network),NI,Hydro,-38.805354,177.151399
42,TWC2201,1835550.0,5529228.0,Manawatu (Powerco),NI,Wind,-40.354267,175.773710
43,TWH0331,1789809.0,5821033.0,Waikato (WEL Networks),NI,Wind,-37.738327,175.154139
44,WDV1101,1842684.0,5533314.0,Southern Hawke's Bay (Scanpower),NI,Wind,-40.315457,175.856067
45,WIL0331,1747405.0,5431065.0,Wellington (Wellington Electricity),NI,Wind,-41.258396,174.759556
46,WKM2201,1844481.0,5743971.0,King Country (The Lines Company),NI,Hydro,-38.419082,175.800363
47,WPA2201,1834680.0,5758417.0,Waipa (Waipa Networks),NI,Hydro,-38.291661,175.683408
48,WPG0331,1404006.0,4918940.0,Dunedin (Aurora Energy),SI,Hydro,-45.855209,170.475388
49,WTK0111,1396285.0,5048037.0,Waitaki (Network Waitaki),SI,Hydro,-44.692099,170.429029
50,WVY1101,1740109.0,5598256.0,Wanganui (Powerco),NI,Wind,-39.754097,174.635503
51,WWD1102,1739027.0,5427096.0,Wellington (Wellington Electricity),NI,Wind,-41.295618,174.660496
52,WWD1103,1739027.0,5427096.0,Wellington (Wellington Electricity),NI,Wind,-41.295618,174.660496
53,HRP2201,NaN,NaN,Hawke's Bay (Unison Networks),NI,Wind,-39.604330,176.753550

In [26]:
keys_in_merged = set(merged_df['POC_Code'].unique())
keys_in_nsp = set(nsp_info['POC_Code'].unique())
missing_keys = keys_in_merged - keys_in_nsp
print("POC_Code values missing in nsp_info:", missing_keys)

POC_Code values missing in nsp_info: {'MAT1102', 'BEN0162', 'KUM0111', 'ANI0111', 'KUM0661', 'COB0661', 'BEN0163'}

In [28]:
lookup_codes = ['ANI0111', 'BEN0163', 'COB0661', 'KUM0661', 'MAT1102', 'KUM0111', 'BEN0162']

# Filter the DataFrame for the lookup codes
filtered_df = merged_df[merged_df['POC_Code'].isin(lookup_codes)].copy()

# Convert DATE column to datetime if not already done
filtered_df['DATE'] = pd.to_datetime(filtered_df['DATE'])

# Extract the year and create a new column
filtered_df['Year'] = filtered_df['DATE'].dt.year

# Get unique POC_Code and Year combinations
result = filtered_df[['POC_Code', 'Year']].drop_duplicates()
print(result)

       POC_Code  Year
0       ANI0111  2000
403     KUM0111  2000
248     COB0661  2000
12481   KUM0111  2001
12326   COB0661  2001
12078   ANI0111  2001
24526   KUM0111  2002
24123   ANI0111  2002
24371   COB0661  2002
36571   KUM0111  2003
36416   COB0661  2003
36168   ANI0111  2003
48616   KUM0111  2004
48213   ANI0111  2004
48461   COB0661  2004
60858   KUM0111  2005
60703   COB0661  2005
60455   ANI0111  2005
73113   COB0661  2006
73268   KUM0111  2006
72865   ANI0111  2006
85678   KUM0111  2007
85523   COB0661  2007
85275   ANI0111  2007
98244   COB0661  2008
98399   KUM0111  2008
97996   ANI0111  2008
111210  KUM0661  2009
111055  COB0661  2009
110993  BEN0163  2009
110962  BEN0162  2009
126907  BEN0162  2010
127031  COB0661  2010
126938  BEN0163  2010
143016  BEN0162  2011
143140  COB0661  2011
143047  BEN0163  2011
159752  COB0661  2012
159659  BEN0162  2012
174983  MAT1102  2012
176365  MAT1102  2013
176148  COB0661  2013
192790  MAT1102  2014
192573  COB0661  2014
208690  COB0661  2015

In [30]:
lookup_codes = ['ANI0111', 'BEN0163', 'COB0661', 'KUM0661', 'MAT1102', 'KUM0111', 'BEN0162']

# Filter the DataFrame for the lookup codes
filtered_df = merged_df[merged_df['POC_Code'].isin(lookup_codes)].copy()

# Convert DATE column to datetime if it's not already
filtered_df['DATE'] = pd.to_datetime(filtered_df['DATE'])

# Create a new column in yyyy-mm format
filtered_df['YearMonth'] = filtered_df['DATE'].dt.strftime('%Y-%m')

# Get unique POC_Code and YearMonth combinations
result = filtered_df[['POC_Code', 'YearMonth']].drop_duplicates()
print(result)

       POC_Code YearMonth
0       ANI0111   2000-01
403     KUM0111   2000-01
248     COB0661   2000-01
1255    COB0661   2000-02
1400    KUM0111   2000-02
...         ...       ...
204642  COB0661   2014-10
205997  COB0661   2014-11
207326  COB0661   2014-12
208690  COB0661   2015-01
210027  COB0661   2015-02

[495 rows x 2 columns]

In [32]:
# Ensure DATE column is in datetime format
merged_df['DATE'] = pd.to_datetime(merged_df['DATE'])

# Filter the DataFrame for dates greater than February 1, 2015
filtered_merged = merged_df[merged_df['DATE'] >= pd.Timestamp('2015-03-01')]

print(filtered_merged.head())

       Fuel_Code POC_Code       DATE   Total_TP
211869     Hydro  TKB2201 2015-03-01  3071228.0
211714     Hydro  ROX1101 2015-03-01   885690.0
211032     Hydro  ARG1101 2015-03-01        0.0
211745     Hydro  ROX2201 2015-03-01  2723561.0
211218     Hydro  BEN2202 2015-03-01  7850310.0

In [34]:
keys_in_merged_after = set(filtered_merged['POC_Code'].unique())
keys_in_nsp = set(nsp_info['POC_Code'].unique())
missing_keys = keys_in_merged_after - keys_in_nsp
print("POC_Code values missing in nsp_info:", missing_keys)

POC_Code values missing in nsp_info: set()

In [36]:
# Load the dataset
#df = pd.read_csv("merged_data.csv")

In [38]:
# Count records before the merge
before_count = filtered_merged.shape[0]

In [40]:
# # Merge on both 'POC_Code' and 'Fuel_Code'
# daily_energy = pd.merge(
#     filtered_merged,
#     nsp_info[['POC_Code', 'Fuel_Code', 'Island', 'Latitude', 'Longitude']],
#     on=['POC_Code', 'Fuel_Code'],
#     how='left'
# )

In [42]:
# # Count records after the merge
# after_count = daily_energy.shape[0]

# print("Record count before merge:", before_count)
# print("Record count after merge:", after_count)

Record count before merge: 167222
Record count after merge: 169080

In [44]:
# duplicates = nsp_info[nsp_info.duplicated(subset=['POC_Code', 'Fuel_Code'], keep=False)]
# print(duplicates)

   POC_Code  NZTM_easting  NZTM_northing                  Network Island  \
16  HWB0331     1404029.0      4918978.0  Dunedin (Aurora Energy)     SI
17  HWB0331     1404029.0      4918978.0      Otago (OtagoNet JV)     SI

   Fuel_Code   Latitude  Longitude
16     Hydro -45.854874   170.4757
17     Hydro -45.854874   170.4757

In [40]:
# Remove the 'Network' column
nsp_info_clean = nsp_info.drop(columns=['Network'])

In [42]:
# Drop duplicates based on POC_Code and Fuel_Code
nsp_info_unique = nsp_info_clean.drop_duplicates(subset=['POC_Code', 'Fuel_Code'])

In [44]:
nsp_info_unique

,POC_Code,NZTM_easting,NZTM_northing,Island,Fuel_Code,Latitude,Longitude
0,ARA2201,1873657.0,5721160.0,NI,Hydro,-38.615891,176.143036
1,ARG1101,1616836.0,5386748.0,SI,Hydro,-41.670851,173.202251
2,ARI1101,1831834.0,5782895.0,NI,Hydro,-38.072026,175.642919
3,ARI1102,1831834.0,5782895.0,NI,Hydro,-38.072026,175.642919
4,ASB0661,1503869.0,5133912.0,SI,Hydro,-43.941637,171.802149
5,ATI2201,1863994.0,5746271.0,NI,Hydro,-38.392831,176.022730
6,AVI2201,1390245.0,5051586.0,SI,Hydro,-44.658443,170.354335
7,BEN2202,1377144.0,5061473.0,SI,Hydro,-44.565596,170.193571
8,BPE0331,1824481.0,5537751.0,NI,Wind,-40.280614,175.640510
9,BWK1101,1375377.0,4908483.0,SI,Hydro,-45.940470,170.102172
10,COL0661,1480658.0,5197735.0,SI,Hydro,-43.363766,171.527122
11,CYD0331,1309790.0,4990370.0,SI,Hydro,-45.180391,169.306224
12,CYD2201,1309790.0,4990370.0,SI,Hydro,-45.180391,169.306224
13,EDG0331,1936285.0,5788677.0,NI,Solar,-37.987259,176.828883
14,GOR0331,1284097.0,4885035.0,SI,Wind,-46.115091,168.911652
15,HWA1101,1712537.0,5619536.0,NI,Hydro,-39.566497,174.310117
16,HWB0331,1404029.0,4918978.0,SI,Hydro,-45.854874,170.475700
18,KOE1101,1673614.0,6082721.0,NI,Solar,-35.396162,173.810632
19,KPO1101,1823029.0,5799542.0,NI,Hydro,-37.924349,175.537461
20,LTN0331,1823277.0,5523360.0,NI,Wind,-40.410452,175.631394
21,LTN2201,1823277.0,5523360.0,NI,Wind,-40.410452,175.631394
22,MAN2201,1153098.0,4943235.0,SI,Hydro,-45.520868,167.277500
23,MAT1101,1934456.0,5774722.0,NI,Hydro,-38.113429,176.814617
24,MHO0331,1807281.0,5505363.0,NI,Hydro,-40.576575,175.448930
25,MTI2201,1839802.0,5751482.0,NI,Hydro,-38.352736,175.744267
26,NMA0331,1242677.0,4861547.0,SI,Wind,-46.305391,168.359527
27,NSY0331,1371044.0,5009253.0,SI,Hydro,-45.033180,170.093353
28,OHA2201,1362883.0,5094304.0,SI,Hydro,-44.265872,170.029212
29,OHB2201,1369516.0,5090545.0,SI,Hydro,-44.301801,170.110551
30,OHC2201,1375175.0,5086098.0,SI,Hydro,-44.343561,170.179492
31,OHK2201,1869462.0,5744408.0,NI,Hydro,-38.407966,176.085969
32,ROT1101,1882790.0,5772814.0,NI,Hydro,-38.148250,176.227041
33,ROX1101,1312313.0,4957442.0,SI,Hydro,-45.477213,169.319136
34,ROX2201,1312313.0,4957442.0,SI,Hydro,-45.477213,169.319136
35,RPO2201,1845189.0,5662388.0,NI,Hydro,-39.153194,175.837443
36,STK0661,1620344.0,5426252.0,SI,Hydro,-41.314941,173.243059
37,TGA0331,1875930.0,5819779.0,NI,Hydro,-37.727716,176.130869
38,TKA0111,1396471.0,5123459.0,SI,Hydro,-44.013807,170.460853
39,TKB2201,1376922.0,5110445.0,SI,Hydro,-44.125161,170.211748
40,TKU2201,1839960.0,5681601.0,NI,Hydro,-38.981721,175.770224
41,TUI1101,1960528.0,5696630.0,NI,Hydro,-38.805354,177.151399
42,TWC2201,1835550.0,5529228.0,NI,Wind,-40.354267,175.773710
43,TWH0331,1789809.0,5821033.0,NI,Wind,-37.738327,175.154139
44,WDV1101,1842684.0,5533314.0,NI,Wind,-40.315457,175.856067
45,WIL0331,1747405.0,5431065.0,NI,Wind,-41.258396,174.759556
46,WKM2201,1844481.0,5743971.0,NI,Hydro,-38.419082,175.800363
47,WPA2201,1834680.0,5758417.0,NI,Hydro,-38.291661,175.683408
48,WPG0331,1404006.0,4918940.0,SI,Hydro,-45.855209,170.475388
49,WTK0111,1396285.0,5048037.0,SI,Hydro,-44.692099,170.429029
50,WVY1101,1740109.0,5598256.0,NI,Wind,-39.754097,174.635503
51,WWD1102,1739027.0,5427096.0,NI,Wind,-41.295618,174.660496
52,WWD1103,1739027.0,5427096.0,NI,Wind,-41.295618,174.660496
53,HRP2201,NaN,NaN,NI,Wind,-39.604330,176.753550

In [46]:
# Now perform the merge on 'POC_Code' and 'Fuel_Code'
daily_energy = pd.merge(
    filtered_merged,
    nsp_info_unique[['POC_Code', 'Fuel_Code', 'Island', 'Latitude', 'Longitude']],
    on=['POC_Code', 'Fuel_Code'],
    how='left'
)

In [48]:
# Check record counts
print("Record count before merge:", before_count)
print("Record count after merge:", daily_energy.shape[0])

Record count before merge: 167222
Record count after merge: 167222

In [27]:
# # Merge the DataFrames on the 'POC_Code' column.
# daily_energy = pd.merge(merged_df, nsp_info[['POC_Code', 'Island', 'Fuel_Code', 'Latitude', 'Longitude']], on='POC_Code', how='left')

In [50]:
daily_energy

       Fuel_Code POC_Code       DATE   Total_TP Island   Latitude   Longitude
0          Hydro  TKB2201 2015-03-01  3071228.0     SI -44.125161  170.211748
1          Hydro  ROX1101 2015-03-01   885690.0     SI -45.477213  169.319136
2          Hydro  ARG1101 2015-03-01        0.0     SI -41.670851  173.202251
3          Hydro  ROX2201 2015-03-01  2723561.0     SI -45.477213  169.319136
4          Hydro  BEN2202 2015-03-01  7850310.0     SI -44.565596  170.193571
...          ...      ...        ...        ...    ...        ...         ...
167217     Hydro  TKB2201 2025-01-31  2317178.0     SI -44.125161  170.211748
167218     Hydro  CYD2201 2025-01-31  3547678.0     SI -45.180391  169.306224
167219     Hydro  TKA0111 2025-01-31   460917.0     SI -44.013807  170.460853
167220     Hydro  WTK0111 2025-01-31  1610301.0     SI -44.692099  170.429029
167221      Wind  WWD1103 2025-01-31   544447.0     NI -41.295618  174.660496

[167222 rows x 7 columns]

In [52]:
filename = "daily_energy_with_nsp.csv"

output_file = os.path.join(_dir, filename)

daily_energy.to_csv(output_file, index=False)

print(f"Merged CSV file saved as {output_file}")

Merged CSV file saved as C:\Users\nwn86\ResearchProject_singlensp\Processed\daily_energy_with_nsp.csv

In [54]:
# Filter data for Hydro and Wind
hydro_df = daily_energy[daily_energy["Fuel_Code"] == "Hydro"]
wind_df = daily_energy[daily_energy["Fuel_Code"] == "Wind"]

In [56]:
hydro_df = hydro_df.groupby(['Fuel_Code','POC_Code', 'DATE'], as_index=False).sum()

In [58]:
wind_df = wind_df.groupby(['Fuel_Code','POC_Code', 'DATE'], as_index=False).sum()

In [60]:
hydro_data = "hydro_data.csv"
output_hydro_file = os.path.join(_dir, hydro_data)

In [62]:
wind_data = "wind_data.csv"
output_wind_file = os.path.join(_dir, wind_data)

In [64]:
# Save to separate CSV files
hydro_df.to_csv(output_hydro_file, index=False)
wind_df.to_csv(output_wind_file, index=False)

print("Hydro and Wind data have been successfully saved to separate CSV files.")

Hydro and Wind data have been successfully saved to separate CSV files.